version: '3.8'

services:
  app1:
    build: .
    container_name: blog-app-1
    environment:
      - MONGO_URL=mongodb://mongo:27017/BlogForAll
      - SECERETE_KEY=$asghar$00$

  app2:
    build: .
    container_name: blog-app-2
    environment:
      - MONGO_URL=mongodb://mongo:27017/BlogForAll
      - SECERETE_KEY=$asghar$00$
    

  mongo:
    image: mongo:6
    container_name: blog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

volumes:
  mongo-data:
